<?php

/**
 * Projeto 2 - PHP CS Fixer
 */
$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__);

return (new PhpCsFixer\Config())
    ->setUsingCache(false)
    ->setRules([
        '@PSR12' => true,
        'no_alias_language_construct_call' => true,
        'no_mixed_echo_print' => [
            'use' => 'echo',
        ],
        'array_syntax' => [
            'syntax' => 'short',
        ],
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_whitespace_before_comma_in_array' => true,
        'normalize_index_brace' => true,
        'trim_array_spaces' => true,
        'whitespace_after_comma_in_array' => true,
        'braces' => [
            'allow_single_line_anonymous_class_with_empty_body' => true,
            'allow_single_line_closure' => true,
            'position_after_functions_and_oop_constructs' => 'same',
            'position_after_control_structures' => 'same',
            'position_after_anonymous_constructs' => 'same',
        ],
        'encoding' => true,
        // 'integer_literal_case' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'native_function_casing' => true,
        'native_function_type_declaration_casing' => true,
        'cast_spaces' => true,
        'lowercase_cast' => true,
        'no_short_bool_cast' => true,
        'no_unset_cast' => true,
        'class_attributes_separation' => [
            'elements' => ['const' => 'none',
                'method' => 'one',
                'property' => 'none',
                'trait_import' => 'none',
            ],
        ],
        'no_null_property_initialization' => true,
        'ordered_class_elements' => true,
        'protected_to_private' => true,
        'self_static_accessor' => true,
        'single_class_element_per_statement' => true,
        'no_empty_comment' => true,
        'single_line_comment_style' => true,
        // 'control_structure_continuation_position' => ['position' => 'same_line'],
        // 'empty_loop_body' => ['style' => 'braces'],
        // 'empty_loop_condition' => ['style' => 'while'],
        'include' => true,
        'no_alternative_syntax' => true,
        'no_superfluous_elseif' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_unneeded_control_parentheses' => true,
        'no_unneeded_curly_braces' => [
            'namespaces' => true,
        ],
        'no_useless_else' => true,
        'simplified_if_return' => true,
        'switch_case_space' => true,
        'switch_continue_to_break' => true,
        'trailing_comma_in_multiline' => true,
        'yoda_style' => ['equal' => false,
            'identical' => false,
            'less_and_greater' => false,
        ],
        'function_typehint_space' => true,
        'lambda_not_used_import' => true,
        'method_argument_space' => true,
        'nullable_type_declaration_for_default_null_value' => true,
        'no_unused_imports' => true,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'explicit_indirect_variable' => true,
        'single_space_after_construct' => true,
        'list_syntax' => [
            'syntax' => 'short',
        ],
        'clean_namespace' => true,
        'no_leading_namespace_whitespace' => true,
        // 'assign_null_coalescing_to_coalesce_equal' => true,
        'binary_operator_spaces' => [
            'default' => 'single_space',
            'operators' => ['^' => 'no_space',
                '*' => 'no_space',
                '**' => 'no_space',
                '/' => 'no_space',
                '%' => 'no_space',
            ],
        ],
        'concat_space' => ['spacing' => 'none'],
        'object_operator_without_whitespace' => true,
        'operator_linebreak' => true,
        'standardize_increment' => true,
        'standardize_not_equals' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_null_coalescing' => true,
        'unary_operator_spaces' => true,
        'echo_tag_syntax' => true,
        'linebreak_after_opening_tag' => true,
        'align_multiline_comment' => ['comment_type' => 'all_multiline'],
        'general_phpdoc_tag_rename' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_empty_phpdoc' => true,
        'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_indent' => true,
        'phpdoc_inline_tag_normalizer' => true,
        'phpdoc_line_span' => [
            'const' => 'single',
            'property' => 'single',
            'method' => 'single',
        ],
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => true,
        'phpdoc_no_empty_return' => true,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_order' => true,
        'phpdoc_return_self_reference' => true,
        'phpdoc_scalar' => true,
        'phpdoc_separation' => true,
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_tag_casing' => true,
        'phpdoc_tag_type' => true,
        'phpdoc_to_comment' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_trim' => true,
        'phpdoc_types' => true,
        'phpdoc_types_order' => true,
        'phpdoc_var_annotation_correct_order' => true,
        'phpdoc_var_without_name' => true,
        'no_useless_return' => true,
        'return_assignment' => true,
        'simplified_null_return' => true,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        'no_empty_statement' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'semicolon_after_instruction' => true,
        'space_after_semicolon' => true,
        'escape_implicit_backslashes' => true,
        'explicit_string_variable' => true,
        'simple_to_complex_string_variable' => true,
        'single_quote' => true,
        'array_indentation' => true,
        'blank_line_before_statement' => true,
        'method_chaining_indentation' => true,
        'no_extra_blank_lines' => true,
        'no_spaces_around_offset' => true,
        // 'types_spaces' => true,
    ])
    ->setFinder($finder);
